// Minimal curated list for demo. You can expand freely.
export const WORDS = [
  "APPLE","CRANE","BRAIN","GHOST","MUSIC","LIGHT","CHORD","PLANT","TRACK","WATER",
  "STONE","BRICK","TEETH","CLOUD","SMILE","ANGEL","RIVER","STORM","SWEET","SHARP",
  "SPIKE","CROWN","SNAKE","FROST","GRASS","LEMON","BERRY","MANGO","CHILI","PEACH",
  "HOUSE","CHAIR","TABLE","COUCH","FLOOR","CELEB","DRIVE","SHARE","SCORE","GUESS",
  "QUICK","SLICK","TRIAL","FINAL","LEVEL","RIGHT","WRONG","THING","NINJA","LASER"
];
